---
- name: Add ansible user
  hosts: 
    - webserver 
    - database
    
  gather_facts: yes
  tasks: 
    - name: Add ansible user to webserver
      when:
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "8" 
      user:
        name: ansible
        groups: wheel
        append: yes
        state: present
        createhome: yes
        shell: /bin/bash
    
    - name: Add ansible user to database
      when:
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_major_version'] == "20" 
      user:
        name: ansible
        groups: sudo
        append: yes
        state: present
        createhome: yes
        shell: /bin/bash

    - name: Set up authorized key for ansible user
      authorized_key: user=ansible key="{{ item }}"
      with_file:
        - /home/ansible/.ssh/id_rsa.pub
      no_log: true
      
    
    - name: Validate the sudoers file before saving
      when:
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "8"
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^# %wheel        ALL=(ALL)       NOPASSWD: ALL'
        line: '%wheel        ALL=(ALL)       NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
    
    - name: Validate the sudoers file before saving
      when:
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_major_version'] == "20"
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^# %wheel        ALL=(ALL)       NOPASSWD: ALL'
        line: '%sudo        ALL=(ALL)       NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s