---
- name: Add ansible user
  hosts: 
    - webserver 
    - database
    
  gather_facts: yes
  tasks: 
    - name: Add ansible user to webserver
      when:
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "8" 
      user:
        name: ansible
        groups: wheel
        append: yes
        state: present
        createhome: yes
        shell: /bin/bash
    
    - name: Add ansible user to database
      when:
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_major_version'] == "20" 
      user:
        name: ansible
        groups: sudo
        append: yes
        state: present
        createhome: yes
        shell: /bin/bash

    - name: Set up authorized key for ansible user
      authorized_key: 
        user=ansible 
        key="{{ item }}"
      with_file:
        - /home/ansible/.ssh/id_rsa.pub
    

         

# option to create systemd file 
# - name: sudo without password for wheel group 
#   copy: 
#     content: '%wheel ALL=(ALL:ALL) NOPASSWD:ALL' 
#     dest: /etc/sudoers.d/wheel_nopasswd 
#     mode: 0440 
# option adding a line in sudoers file 
# NOTE: Fully quoted because of the ': ' on the line. See the Gotchas in the YAML docs. 

 