---
- name: Setup database
  hosts: database
  gather_facts: yes
  become: yes
  vars_files: vars/lamp_vars.yaml
  tasks: 
    - name: Install MariaDB
      when: ansible_facts['distribution'] == "Ubuntu"
      #when: ansible_facts['pkg_mgr'] == "apt"
      apt:
        update_cache: yes
        name: "{{ mariadb_package_name }}"
        state: present

    - name: Start & Enable MariaDB
      when: ansible_facts['service_mgr'] == "systemd"
      systemd:
        name: "{{ mariadb_service_name }}"
        state: started
        enabled: yes
      
    
 
    - name: Create a new database with name 'wpdb'
      mysql_db:
        name: wpdb
        state: present

        
    - name: Removes all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent

    
    - name: create a database user
      mysql_user:
        name: wpuser 
        password: "{{ mysql_passwd }}"
        priv: '*.*:ALL'
        state: present

    - name: Managing mariadb
      block:
        - name: Adding database - wpdb
          mysql_db: 
            name: wpdb
            priv: '*.*:ALL'
            host: 161.35.117.189
            login_unix_socket: socket=/var/run/mysqld/mysqld.sock
            state: present
              
            
        - name: Adding user - wpuser 
          mysql_user:
            name: wpuser
            state: present
            host: webserver
            priv: 'wpuser.wpdb:ALL' 
            login_unix_socket: /var/run/mysqld/mysqld.sock
            login_host: database
          when: result is succeeded

        - name: restart mariadb
          systemd:
            name: mariadb
            state: restarted
    