---
- name: Manage mariadb and secure firewalld on database
  hosts: database 
  become: yes
  vars_files: vars/lamp_vars.yaml
  tasks: 
    - name: Installing firewall
      apt:
        name: firewalld
        state: present

    - name: Disabale SELinux
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address            ='
        line: 'bind-address            = 0.0.0.0'   

    - name: Open 3306 port
      firewalld:
        port: 3306/tcp
        zone: public
        permanent: true
        state: enabled 
        immediate: yes 
      notify: restart mariadb 

    - name: Managing mariadb
      block:
        - name: Adding database - wpdb
          mysql_db: 
            name: wpdb
            state: present
            login_unix_socket: /var/run/mysqld/mysqld.sock
    
    - name: Adding user - wpuser
      mysql_user:
        name: wpuser
        state: present
        host: webserver
        priv: 'wpuser.wpdb:ALL' 
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_host: database
      when: result is succeeded
  handlers:
    - name: restart mariadb
      systemd:
        name: mariadb
        state: restarted
