---
- name: Install and Update Packages
  hosts: 
    - webserver
    - database
  gather_facts: yes
  become: yes
  tasks: 
    - name: Update Packages on webserver (CentOS8)
      when: ansible_facts["pkg_mgr"] ==  "dnf"
      dnf:
        name: "*"
        state: latest

    - name: Install Packages
      when: ansible_facts["pkg_mgr"] ==  "dnf"
      dnf:
        name: epel-release
      register: task_result

    - name: Install vim, curl, wget, git
      when: 
        - ansible_facts["pkg_mgr"] ==  "dnf"
        - task_result is succeeded
      dnf:
        name: 
          - vim
          - curl
          - wget
          - git
          - python2-PyMySQL
        state: latest

    - name: Update Packages on database (Ubuntu)
      when: ansible_facts["pkg_mgr"] == "apt"
      apt:
        name: "*"
        state: fixed
    
    