---
- name: Adding Users
  hosts: webserver
  gather_facts: yes
  vars: 
    - user_pass: "$4$myrandomsalt$qMpBEIY5agCrLIJnNNsaXIg/nxU3TZN/13R2cx8CHlVriSdozJ52Q1eYvEVCDKG0QMiCKiZQAaB6ZkRuufnTmg/"
  tasks:
    - name: adding user in CentOS server
      when: ansible_facts["distribution"] == "CentOS"
      user: 
        name: ansible
        uid: 1800
        groups: whell
        password: "{{ user_pass }}"
    - name: Add public key
      authorised_key: 
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}
